### ISSUE TITLE
"Stolen" treasure not detectable 

### ISSUE THREAD

**Issue by michaelbromley** [cprerovsky/rest-quest#6]
This is kind of an edge case but I think I've been running into in testing my client.

When player A moves onto a treasure tile, the treasure key is deleted, so when he gets the new view, standing on what _was_ the treasure tile, the new view says that this tile (centre tile) has no treasure (since the player has picked it up). So in order for us to track that our player actually has the treasure, we need to see the the tile we are about to move to has treasure, and then assume that we picked it up when we move to it.

However, if player B moves onto that tile first, the treasure will be picked up and then when player A moves onto it, player A will have no way of knowing that the treasure was already "stolen" by player B, and will falsely assume that _he_ has picked it up. Only the server knows internally who actually picked up the treasure.

Am I understanding this correctly? Since the server code is new to me, I may be misunderstanding the way it works.

If I am correct, then it may be an idea to indicate somehow when a player moves onto a treasure tile that the treasure is still actually there to be picked up.

**Comment by escitalopram** [comment]
Every view comes with a boolean that says if you are currently carrying a treasure or not.

**Comment by michaelbromley** [comment]
Yes, silly me. Thanks!
